version: "3.8"

services:
  mongo:
    image: mongo:6
    container_name: dd-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    volumes:
      - mongo_data:/data/db
    networks:
      - dd-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: aksarsr/dd-backend:latest
    container_name: dd-backend
    restart: always
    environment:
      MONGO_URL: mongodb://root:rootpassword@mongo:27017/dd_db?authSource=admin
      PORT: 3000
    depends_on:
      - mongo
    ports:
      - "3000:3000"
    networks:
      - dd-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: aksarsr/dd-frontend:latest
    container_name: dd-frontend
    restart: always
    depends_on:
      - backend
    networks:
      - dd-network

  nginx:
    image: nginx:alpine
    container_name: dd-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - dd-network

volumes:
  mongo_data:

networks:
  dd-network:

    driver: bridge
